data:
  dir: data/
  train_file: trainItem2.txt
  test_file: testItem2.txt
  track_file: trackData2.txt
  album_file: albumData2.txt
  artist_file: artistData2.txt
  genre_file: genreData2.txt
pipeline:
  top_n: 100
  run_name: baseline_v1
  candidate_strategy: unseen
  soft_rank_probs:
  - 0.99
  - 0.95
  - 0.9
  - 0.1
  - 0.05
  - 0.01
  eval_auc: true
scorer:
  weights:
    genre_match: 0.35
    artist_match: 0.3
    album_match: 0.15
    popularity: 0.15
    novelty: 0.05
  popularity_log_base: 10
  rule1_weights:
    hw4_track_score: !!python/object/apply:numpy._core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      zczMzMzM3D8=
    hw4_album_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      mpmZmZmZyT8=
    hw4_artist_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      mpmZmZmZuT8=
    hw4_genre_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      mpmZmZmZqT8=
    hw4_pop_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      mpmZmZmZyT8=
  rule2_weights:
    w_content: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      MzMzMzMz0z8=
    w_svd: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      AAAAAAAA0D8=
    w_uu: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      zczMzMzM3D8=
  rule3_alpha: 0.2
cold_start:
  new_user_strategy: global_popularity
  new_track_strategy: artist_proxy
  cold_track_slot_fraction: 0.1
  intra_album_agg: mean
collab_filtering:
  cf_top_k: 20
  n_components: 20
lgbm:
  n_estimators: 1000
  learning_rate: 0.02
  num_leaves: 127
  min_child_samples: 10
  subsample: 0.8
  colsample_bytree: 0.8
  eval_at:
  - 3
  max_train_users: 40000
  max_interactions_per_user: 50
  n_eval_users: 3000
features:
  cache_dir: .cache/features/
  force_recompute: false
